build(deps): bump pylint and pyyaml in dev requirements
This increases the version of pylint, as a speculative change to see if it
addresses linting failures of a separate PR:

> AttributeError: 'Attribute' object has no attribute 'value'

The version of pyyaml is bumped because the existing version has trouble
building locally on my computer, raising:

> AttributeError: cython_sources

The changes in the code are to get it to pass pylint checks with its newer
version.